# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apropos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 480)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(60, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.button_fermer = QtWidgets.QPushButton(Dialog)
        self.button_fermer.setGeometry(QtCore.QRect(400, 440, 75, 30))
        self.button_fermer.setObjectName("button_fermer")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 150, 481, 281))
        self.listView.setObjectName("listView")

        self.retranslateUi(Dialog)
        self.button_fermer.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "A propos"))
        self.label_1.setText(_translate("Dialog", "A propos"))
        self.label_2.setText(_translate("Dialog", "log SWL 1.0"))
        self.label_3.setText(_translate("Dialog", "Logiciel pour les écouteurs SWL"))
        self.button_fermer.setText(_translate("Dialog", "Fermer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
