# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apropos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 480)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.logo_label = QtWidgets.QLabel(Dialog)
        self.logo_label.setGeometry(QtCore.QRect(160, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logo_label.setFont(font)
        self.logo_label.setObjectName("logo_label")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(160, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.button_fermer = QtWidgets.QPushButton(Dialog)
        self.button_fermer.setGeometry(QtCore.QRect(400, 440, 75, 30))
        self.button_fermer.setObjectName("button_fermer")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 121, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 140, 481, 281))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)

        self.retranslateUi(Dialog)
        self.button_fermer.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "A propos"))
        self.logo_label.setText(_translate("Dialog", "Version 1.0"))
        self.label_1.setText(_translate("Dialog", "logSWL"))
        self.label_2.setText(_translate("Dialog", "Logbook pour les radio-écouteurs"))
        self.button_fermer.setText(_translate("Dialog", "Fermer"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "20/09/2024   Début du codage de cette application"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "06/10/2024   L\'application est fonctionnel"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "10/10/2024   Mise en ligne de la v1.0 sur github"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "15/10/2024   Ajout système de traduction"))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "20/10/2024   intégration API QRZCQ"))

        self.listWidget.sortItems(Qt.AscendingOrder)  # Tri dans le bon ordre
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
