# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fen_station.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fen_station(object):
    def setupUi(self, fen_station):
        fen_station.setObjectName("fen_station")
        fen_station.resize(342, 376)
        self.frame_station = QtWidgets.QFrame(fen_station)
        self.frame_station.setGeometry(QtCore.QRect(0, 0, 341, 381))
        self.frame_station.setObjectName("frame_station")
        self.label_qrz = QtWidgets.QLabel(self.frame_station)
        self.label_qrz.setGeometry(QtCore.QRect(100, 70, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_qrz.setFont(font)
        self.label_qrz.setAccessibleName("")
        self.label_qrz.setAccessibleDescription("")
        self.label_qrz.setTextFormat(QtCore.Qt.PlainText)
        self.label_qrz.setObjectName("label_qrz")
        self.label_titre = QtWidgets.QLabel(self.frame_station)
        self.label_titre.setGeometry(QtCore.QRect(0, 0, 341, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_titre.setFont(font)
        self.label_titre.setAccessibleName("")
        self.label_titre.setTextFormat(QtCore.Qt.PlainText)
        self.label_titre.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titre.setObjectName("label_titre")
        self.bouton_enregister = QtWidgets.QPushButton(self.frame_station)
        self.bouton_enregister.setGeometry(QtCore.QRect(70, 320, 75, 30))
        self.bouton_enregister.setObjectName("bouton_enregister")
        self.bouton_annuler = QtWidgets.QPushButton(self.frame_station)
        self.bouton_annuler.setGeometry(QtCore.QRect(205, 320, 75, 30))
        self.bouton_annuler.setObjectName("bouton_annuler")
        self.label_mygrid = QtWidgets.QLabel(self.frame_station)
        self.label_mygrid.setGeometry(QtCore.QRect(110, 140, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_mygrid.setFont(font)
        self.label_mygrid.setAccessibleName("")
        self.label_mygrid.setAccessibleDescription("")
        self.label_mygrid.setTextFormat(QtCore.Qt.PlainText)
        self.label_mygrid.setObjectName("label_mygrid")
        self.saisie_mygrid = QtWidgets.QLineEdit(self.frame_station)
        self.saisie_mygrid.setGeometry(QtCore.QRect(100, 160, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saisie_mygrid.setFont(font)
        self.saisie_mygrid.setInputMask("AA99aa")
        self.saisie_mygrid.setAlignment(QtCore.Qt.AlignCenter)
        self.saisie_mygrid.setObjectName("saisie_mygrid")
        self.saisie_qrz = QtWidgets.QLineEdit(self.frame_station)
        self.saisie_qrz.setGeometry(QtCore.QRect(90, 90, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saisie_qrz.setFont(font)
        self.saisie_qrz.setInputMask("")
        self.saisie_qrz.setText("")
        self.saisie_qrz.setMaxLength(14)
        self.saisie_qrz.setAlignment(QtCore.Qt.AlignCenter)
        self.saisie_qrz.setObjectName("saisie_qrz")
        self.label_exemple = QtWidgets.QLabel(self.frame_station)
        self.label_exemple.setGeometry(QtCore.QRect(210, 140, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_exemple.setFont(font)
        self.label_exemple.setObjectName("label_exemple")
        self.label_qthname = QtWidgets.QLabel(self.frame_station)
        self.label_qthname.setGeometry(QtCore.QRect(90, 210, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_qthname.setFont(font)
        self.label_qthname.setAccessibleName("")
        self.label_qthname.setAccessibleDescription("")
        self.label_qthname.setTextFormat(QtCore.Qt.PlainText)
        self.label_qthname.setObjectName("label_qthname")
        self.saisie_qthname = QtWidgets.QLineEdit(self.frame_station)
        self.saisie_qthname.setGeometry(QtCore.QRect(80, 230, 201, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saisie_qthname.setFont(font)
        self.saisie_qthname.setInputMask("")
        self.saisie_qthname.setAlignment(QtCore.Qt.AlignCenter)
        self.saisie_qthname.setObjectName("saisie_qthname")

        self.retranslateUi(fen_station)
        self.bouton_annuler.clicked.connect(fen_station.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fen_station)
        fen_station.setTabOrder(self.saisie_qrz, self.saisie_mygrid)
        fen_station.setTabOrder(self.saisie_mygrid, self.bouton_enregister)
        fen_station.setTabOrder(self.bouton_enregister, self.bouton_annuler)

    def retranslateUi(self, fen_station):
        _translate = QtCore.QCoreApplication.translate
        fen_station.setWindowTitle(_translate("fen_station", "Ma station"))
        self.label_qrz.setText(_translate("fen_station", "MY QRZ"))
        self.label_titre.setText(_translate("fen_station", "Configurer ma station"))
        self.bouton_enregister.setText(_translate("fen_station", "Valider"))
        self.bouton_annuler.setText(_translate("fen_station", "Annuler"))
        self.label_mygrid.setText(_translate("fen_station", "LOCATOR"))
        self.label_exemple.setText(_translate("fen_station", "Ex: JN18eu"))
        self.label_qthname.setText(_translate("fen_station", "QTH name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fen_station = QtWidgets.QDialog()
    ui = Ui_fen_station()
    ui.setupUi(fen_station)
    fen_station.show()
    sys.exit(app.exec_())
